services:
  devcontainer:
    build:
      context: .
    shm_size: '2gb'
    volumes:
      - ../..:/workspaces:rw,cached
    init: true
    command: sleep infinity
    network_mode: service:nginx
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ../www:/usr/share/nginx/html:ro
